<?php  
	include 'php/backend/maestros/conexion.php';
	$cn = new Database();
	$st = $cn->prepare("SELECT id_slider, url_imagen FROM slider WHERE id_slider = 1");
	$st->execute();
	$result = $st->fetch();
	$st = $cn->prepare("SELECT id_slider, url_imagen FROM slider WHERE id_slider = 2");
	$st->execute();
	$result2 = $st->fetch();
	$st = $cn->prepare("SELECT id_slider, url_imagen FROM slider WHERE id_slider = 3");
	$st->execute();
	$result3 = $st->fetch();
	$st = $cn->prepare("SELECT id_slider, url_imagen FROM slider WHERE id_slider = 4");
	$st->execute();
	$result4 = $st->fetch();
	$st = $cn->prepare("SELECT titulo_seccion, descripcion, img_seccion FROM secciones WHERE id_seccion = 1");
	$st->execute();
	$result5 = $st->fetch();
	$st = $cn->prepare("SELECT titulo_seccion, descripcion, img_seccion FROM secciones WHERE id_seccion = 2");
	$st->execute();
	$result6 = $st->fetch();
	$st = $cn->prepare("SELECT titulo_seccion, descripcion, img_seccion FROM secciones WHERE id_seccion = 3");
	$st->execute();
	$result7 = $st->fetch();
	$st = $cn->prepare("SELECT titulo_seccion FROM secciones WHERE id_seccion = 4");
	$st->execute();
	$result8 = $st->fetch();
	$st = $cn->prepare("SELECT valor, img_valor FROM valores WHERE id_valor = 1");
	$st->execute();
	$result9 = $st->fetch();
	$st = $cn->prepare("SELECT valor, img_valor FROM valores WHERE id_valor = 2");
	$st->execute();
	$result10 = $st->fetch();
	$st = $cn->prepare("SELECT valor, img_valor FROM valores WHERE id_valor = 3");
	$st->execute();
	$result11 = $st->fetch();
	$st = $cn->prepare("SELECT valor, img_valor FROM valores WHERE id_valor = 4");
	$st->execute();
	$result12 = $st->fetch();
	$st = $cn->prepare("SELECT valor, img_valor FROM valores WHERE id_valor = 5");
	$st->execute();
	$result13 = $st->fetch();
	$st = $cn->prepare("SELECT valor, img_valor FROM valores WHERE id_valor = 6");
	$st->execute();
	$result14 = $st->fetch();
	$st = $cn->prepare("SELECT * FROM servicios WHERE id_servicio = 1");
	$st->execute();
	$result15 = $st->fetch();
	$st = $cn->prepare("SELECT servicio FROM listado_servicios WHERE id_servicio = 1");
	$st->execute();
	$result16 = $st->fetchAll();
	$st = $cn->prepare("SELECT * FROM servicios WHERE id_servicio = 2");
	$st->execute();
	$result17 = $st->fetch();
	$st = $cn->prepare("SELECT servicio FROM listado_servicios WHERE id_servicio = 2");
	$st->execute();
	$result18 = $st->fetchAll();
	$st = $cn->prepare("SELECT * FROM servicios WHERE id_servicio = 3");
	$st->execute();
	$result19 = $st->fetch();
	$st = $cn->prepare("SELECT servicio FROM listado_servicios WHERE id_servicio = 3");
	$st->execute();
	$result20 = $st->fetchAll();
	$st = $cn->prepare("SELECT * FROM servicios WHERE id_servicio = 4");
	$st->execute();
	$result21 = $st->fetch();
	$st = $cn->prepare("SELECT servicio FROM listado_servicios WHERE id_servicio = 4");
	$st->execute();
	$result22 = $st->fetchAll();
	$st = $cn->prepare("SELECT * FROM servicios WHERE id_servicio = 5");
	$st->execute();
	$result23 = $st->fetch();
	$st = $cn->prepare("SELECT servicio FROM listado_servicios WHERE id_servicio = 5");
	$st->execute();
	$result24 = $st->fetchAll();
?>