<?php  
	session_start();
	include '../maestros/conexion.php';
	include '../librerias/fpdf.php';
	date_default_timezone_set("America/El_Salvador");
	$cn = new Database();
	$report = new FPDF();
	$report->AddFont('Poiret One','','PoiretOne-Regular.php');
	$report->AddFont('Pacifico','','Pacifico.php');
	$report->AddFont('Open Sans','','OpenSans-Semibold.php');
	$report->AddFont('Josefin Sans','','JosefinSans-Regular.php');
	$report->AddPage();
	$report->SetMargins(15, 15 , 15);
	$report->SetAutoPageBreak(true, 15); 
	$report->Image('../img/logo_report.png', 10, 7, 60, 30, 'PNG');
	$report->SetFont('Poiret One','', 25);
	$report->Cell(60, 10, '', 0);
	$report->Cell(90, 20, utf8_decode('Servicios Globales Logísticos'), 0);
	$report->Ln(20);
	$report->SetFont('Josefin Sans','', 25);
	$report->Cell(32, 10, '', 0);
	$report->Cell(90, 20, utf8_decode('Reporte individual de mercancías'), 0);
	$report->Ln(20);
	$report->SetFont('Josefin Sans', '', 12);
	$report->Cell(50, 10, 'Reporte generado por: '.$_SESSION['nombre'], 0);
	$report->Ln(15);
    $report->SetDrawColor(4,0,181);
    $report->SetLineWidth(.3);
	$report->SetFont('Open Sans', '', 9);
	$report->Cell(90, 8, utf8_decode('Datos'), 1, 0, 'C');
	$report->Cell(90, 8, utf8_decode('Detalle'), 1, 0, 'C');
	$report->Ln(8);
	$report->SetFont('Josefin Sans', '', 10);
	$st = $cn->prepare("SELECT numero_dm, codigo_merc, nombre_merc, cant_cajas_merc, precio_unitario_merc,
		precio_venta_merc, botellas, litros, cant_caja_merc, valor_merc, ml_merc, pbc, porc_alic, alicuota, porc_elc, elc,
		porc_alch_merc, bruto_ti_merc, nombre_tipo_mercancia, nombre_empresa, porc_dai, dai
		FROM mercancias m INNER JOIN tipo_mercancias t INNER JOIN empresas e INNER JOIN numerosdm n ON m.id_tipo_merc=t.id_tipo_merc 
		AND m.id_empresa=e.id_empresa AND m.id_dm=n.id_dm WHERE id_merc = ?");
	$st->bindParam(1, $_GET['id']);
	$st->execute();
	$resultado = $st->fetch();
	$st = $cn->prepare("SELECT flete, seguro, gastos, cif FROM mercancias WHERE id_merc = ?");
    $st->bindParam(1, $_GET['id']);
    $st->execute();
    $res3 = $st->fetch();
	$report->Cell(90, 8, utf8_decode('Código'), 1, 0, 'C');
	$report->Cell(90, 8, utf8_decode($resultado['codigo_merc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Nombre'), 1, 0, 'C');
	$report->Cell(90, 8, utf8_decode(html_entity_decode($resultado['nombre_merc'])), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Cajas'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['cant_cajas_merc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Precio unitario'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['precio_unitario_merc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Valor'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['valor_merc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Precio de venta'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['precio_venta_merc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Cantidad por caja'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['cant_caja_merc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Mililítros'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['ml_merc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Porcentaje de alcohol'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['porc_alch_merc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Botellas'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['botellas']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Litros'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['litros']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Bruto total'), 1, 0, 'C');
	$report->Cell(90, 8, '$'.html_entity_decode($resultado['bruto_ti_merc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('PBC'), 1, 0, 'C');
	$report->Cell(90, 8, '$'.html_entity_decode($resultado['pbc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Porcentaje alicuota'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['porc_alic']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Alicuota'), 1, 0, 'C');
	$report->Cell(90, 8, '$'.html_entity_decode($resultado['alicuota']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Porcentaje ELC'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['porc_elc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('ELC'), 1, 0, 'C');
	$report->Cell(90, 8, '$'.html_entity_decode($resultado['elc']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Flete'), 1, 0, 'C');
	$report->Cell(90, 8, '$'.html_entity_decode($res3['flete']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Seguros'), 1, 0, 'C');
	$report->Cell(90, 8, '$'.html_entity_decode($res3['seguro']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Gastos'), 1, 0, 'C');
	$report->Cell(90, 8, '$'.html_entity_decode($res3['gastos']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('CIF'), 1, 0, 'C');
	$report->Cell(90, 8, '$'.html_entity_decode($res3['cif']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('Porcentaje DAI'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['porc_dai']), 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(90, 8, utf8_decode('DAI'), 1, 0, 'C');
	$report->Cell(90, 8, html_entity_decode($resultado['dai']), 1, 0, 'C');
	$report->Ln(15);
	$report->Cell(60,10,'Fecha: '.date("d-m-Y"),0,0,'C');
	$report->Cell(60,10,utf8_decode('Página ').$report->PageNo(),0,0,'C');
	$report->Cell(60,10,'Hora: '.date("H:i:s"),0,0,'C');
	$report->Output();
?>