<?php  
	session_start();
	include '../maestros/conexion.php';
	include '../librerias/fpdf.php';
	date_default_timezone_set("America/El_Salvador");
	$cn = new Database();
	$report = new FPDF();
	$report->AddFont('Poiret One','','PoiretOne-Regular.php');
	$report->AddFont('Pacifico','','Pacifico.php');
	$report->AddFont('Open Sans','','OpenSans-Semibold.php');
	$report->AddFont('Josefin Sans','','JosefinSans-Regular.php');
	$report->AddPage();
	$report->SetMargins(15, 15 , 15);
	$report->SetAutoPageBreak(true, 15); 
	$report->Image('../img/logo_report.png', 10, 7, 60, 30, 'PNG');
	$report->SetFont('Poiret One','', 25);
	$report->Cell(60, 10, '', 0);
	$report->Cell(90, 20, utf8_decode('Servicios Globales Logísticos'), 0);
	$report->Ln(20);
	$report->SetFont('Josefin Sans','', 25);
	$report->Cell(40, 10, '', 0);
	$report->Cell(90, 20, utf8_decode('Historial de mercancías retiradas'), 0);
	$report->Ln(20);
	$report->SetFont('Josefin Sans', '', 12);
	$report->Cell(50, 10, 'Empresa: '.$_SESSION['name'], 0);
	$report->Ln(15);
    $report->SetDrawColor(4,0,181);
    $report->SetLineWidth(.3);
	$report->SetFont('Open Sans', '', 9);
	$report->Cell(45, 8, utf8_decode('Nombre'), 1, 0, 'C');
	$report->Cell(45, 8, utf8_decode('Cantidad retirada'), 1, 0, 'C');
	$report->Cell(45, 8, utf8_decode('Precio unitario'), 1, 0, 'C');
	$report->Cell(45, 8, utf8_decode('Precio de venta'), 1, 0, 'C');
	$report->Ln(8);
	$report->SetFont('Josefin Sans', '', 10);
	$st = $cn->prepare("SELECT id_comprobante, nombre_merc_c, cantidad_cajas, precio_unitario, precio_venta FROM comprobantes c INNER JOIN numerosdm n ON c.id_dm=n.id_dm WHERE id_empresa = ? ORDER BY id_comprobante ASC");
	$st->bindParam(1, $_SESSION['code']);
	$st->execute();
	$resultado = $st->fetchAll();
	foreach ($resultado as $key => $value) {
		$report->Cell(45, 8, utf8_decode(html_entity_decode($value['nombre_merc_c'])), 1, 0, 'C');
		$report->Cell(45, 8, html_entity_decode($value['cantidad_cajas']), 1, 0, 'C');
		$report->Cell(45, 8, html_entity_decode($value['precio_unitario']), 1, 0, 'C');
		$report->Cell(45, 8, html_entity_decode($value['precio_venta']), 1, 0, 'C');
		$report->Ln(8);
	}
	$st = $cn->prepare("SELECT SUM(elc_m) AS sum1 FROM comprobantes c INNER JOIN numerosdm n ON c.id_dm=n.id_dm WHERE id_empresa = ?");
	$st->bindParam(1, $_SESSION['code']);
	$st->execute();
	$res = $st->fetch();
	$st = $cn->prepare("SELECT SUM(alicuota_m) AS sum2 FROM comprobantes c INNER JOIN numerosdm n ON c.id_dm=n.id_dm WHERE id_empresa = ?");
	$st->bindParam(1, $_SESSION['code']);
	$st->execute();
	$res1 = $st->fetch();
	$st = $cn->prepare("SELECT SUM(dai_m) AS sum3 FROM comprobantes c INNER JOIN numerosdm n ON c.id_dm=n.id_dm WHERE id_empresa = ?");
	$st->bindParam(1, $_SESSION['code']);
	$st->execute();
	$res2 = $st->fetch();
	$st = $cn->prepare("SELECT cif FROM numerosdm WHERE empresa = ?");
	$st->bindParam(1, $_SESSION['name']);
	$st->execute();
	$res3 = $st->fetch();
	$iva = ($res['sum1'] + $res1['sum2'] + $res2['sum3'] + $res3['cif']) * 0.13;
	$totalImp = $res['sum1'] + $res1['sum2'] + $res2['sum3'] + $res3['cif'] + $iva;
	$report->SetFont('Open Sans', '', 9);
	$report->Cell(90, 8, utf8_decode('IVA'), 1, 0, 'C');
	$report->SetFont('Josefin Sans', '', 10);
	$report->Cell(90, 8, $iva, 1, 0, 'C');
	$report->Ln(8);
	$report->SetFont('Open Sans', '', 9);
	$report->Cell(90, 8, utf8_decode('Total impuestos'), 1, 0, 'C');
	$report->SetFont('Josefin Sans', '', 10);
	$report->Cell(90, 8, $totalImp, 1, 0, 'C');
	$report->Ln(8);
	$report->Cell(60,10,'Fecha: '.date("d-m-Y"),0,0,'C');
	$report->Cell(60,10,utf8_decode('Página ').$report->PageNo(),0,0,'C');
	$report->Cell(60,10,'Hora: '.date("H:i:s"),0,0,'C');
	$report->Output();
?>